language: python
python:
  - "3.4"
  - "3.3"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
  - "3.2"
# It would be nice to at least monitor 2.x.
# But no tests currently get run. See #16.
matrix:
  fast_finish: true
  allow_failures:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.5.0b3"
    - python: "3.5-dev"
    - python: "nightly"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
  # Download bitcoind
  - wget https://bitcoin.org/bin/bitcoin-core-0.11.0/bitcoin-0.11.0-linux64.tar.gz
  - tar -xzvf bitcoin-0.11.0-linux64.tar.gz
  - cp bitcoin-0.11.0/bin/bitcoind bitcoind
# command to run tests
script:
  - python -m unittest
